### ISSUE TITLE
loading rasterio fails

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/ndwi2watermask#2]
Following error occurs:

```>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/stud09/martinsd/local/miniconda2/envs/raster/lib/python2.7/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: /lib64/libk5crypto.so.3: symbol k5_once, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference```

**Comment by jmigueldelgado** [comment]
Could be solved by following this comment: https://github.com/conda-forge/libgdal-feedstock/issues/9#issuecomment-325294341 , ie introducing `export LD_LIBRARY_PATH=""` in the job preamble.
